/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedScoutReportRouteImport } from './routes/_authenticated/scout-report'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTradeAnalyzerRouteImport } from './routes/_authenticated/trade-analyzer'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedLabFormsRouteImport } from './routes/_authenticated/lab/forms'
import { Route as AuthenticatedLabLiftRouteImport } from './routes/_authenticated/lab/lift'
import { Route as AuthenticatedLabLoginRouteImport } from './routes/_authenticated/lab/login'
import { Route as AuthenticatedLabPaletteRouteImport } from './routes/_authenticated/lab/palette'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScoutReportRoute =
  AuthenticatedScoutReportRouteImport.update({
    id: '/scout-report',
    path: '/scout-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeAnalyzerRoute =
  AuthenticatedTradeAnalyzerRouteImport.update({
    id: '/trade-analyzer',
    path: '/trade-analyzer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabFormsRoute = AuthenticatedLabFormsRouteImport.update({
  id: '/lab/forms',
  path: '/lab/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabLiftRoute = AuthenticatedLabLiftRouteImport.update({
  id: '/lab/lift',
  path: '/lab/lift',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabLoginRoute = AuthenticatedLabLoginRouteImport.update({
  id: '/lab/login',
  path: '/lab/login',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabPaletteRoute = AuthenticatedLabPaletteRouteImport.update({
  id: '/lab/palette',
  path: '/lab/palette',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/scout-report': typeof AuthenticatedScoutReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trade-analyzer': typeof AuthenticatedTradeAnalyzerRoute
  '/users': typeof AuthenticatedUsersRoute
  '/lab/forms': typeof AuthenticatedLabFormsRoute
  '/lab/lift': typeof AuthenticatedLabLiftRoute
  '/lab/login': typeof AuthenticatedLabLoginRoute
  '/lab/palette': typeof AuthenticatedLabPaletteRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/scout-report': typeof AuthenticatedScoutReportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/trade-analyzer': typeof AuthenticatedTradeAnalyzerRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/lab/forms': typeof AuthenticatedLabFormsRoute
  '/lab/lift': typeof AuthenticatedLabLiftRoute
  '/lab/login': typeof AuthenticatedLabLoginRoute
  '/lab/palette': typeof AuthenticatedLabPaletteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/scout-report': typeof AuthenticatedScoutReportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/trade-analyzer': typeof AuthenticatedTradeAnalyzerRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/lab/forms': typeof AuthenticatedLabFormsRoute
  '/_authenticated/lab/lift': typeof AuthenticatedLabLiftRoute
  '/_authenticated/lab/login': typeof AuthenticatedLabLoginRoute
  '/_authenticated/lab/palette': typeof AuthenticatedLabPaletteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/scout-report'
    | '/settings'
    | '/trade-analyzer'
    | '/users'
    | '/lab/forms'
    | '/lab/lift'
    | '/lab/login'
    | '/lab/palette'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/scout-report'
    | '/settings'
    | '/trade-analyzer'
    | '/users'
    | '/'
    | '/lab/forms'
    | '/lab/lift'
    | '/lab/login'
    | '/lab/palette'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/_authenticated/scout-report'
    | '/_authenticated/settings'
    | '/_authenticated/trade-analyzer'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/lab/forms'
    | '/_authenticated/lab/lift'
    | '/_authenticated/lab/login'
    | '/_authenticated/lab/palette'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scout-report': {
      id: '/_authenticated/scout-report'
      path: '/scout-report'
      fullPath: '/scout-report'
      preLoaderRoute: typeof AuthenticatedScoutReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade-analyzer': {
      id: '/_authenticated/trade-analyzer'
      path: '/trade-analyzer'
      fullPath: '/trade-analyzer'
      preLoaderRoute: typeof AuthenticatedTradeAnalyzerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/forms': {
      id: '/_authenticated/lab/forms'
      path: '/lab/forms'
      fullPath: '/lab/forms'
      preLoaderRoute: typeof AuthenticatedLabFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/lift': {
      id: '/_authenticated/lab/lift'
      path: '/lab/lift'
      fullPath: '/lab/lift'
      preLoaderRoute: typeof AuthenticatedLabLiftRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/login': {
      id: '/_authenticated/lab/login'
      path: '/lab/login'
      fullPath: '/lab/login'
      preLoaderRoute: typeof AuthenticatedLabLoginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/palette': {
      id: '/_authenticated/lab/palette'
      path: '/lab/palette'
      fullPath: '/lab/palette'
      preLoaderRoute: typeof AuthenticatedLabPaletteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedScoutReportRoute: typeof AuthenticatedScoutReportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTradeAnalyzerRoute: typeof AuthenticatedTradeAnalyzerRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLabFormsRoute: typeof AuthenticatedLabFormsRoute
  AuthenticatedLabLiftRoute: typeof AuthenticatedLabLiftRoute
  AuthenticatedLabLoginRoute: typeof AuthenticatedLabLoginRoute
  AuthenticatedLabPaletteRoute: typeof AuthenticatedLabPaletteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedScoutReportRoute: AuthenticatedScoutReportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTradeAnalyzerRoute: AuthenticatedTradeAnalyzerRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLabFormsRoute: AuthenticatedLabFormsRoute,
  AuthenticatedLabLiftRoute: AuthenticatedLabLiftRoute,
  AuthenticatedLabLoginRoute: AuthenticatedLabLoginRoute,
  AuthenticatedLabPaletteRoute: AuthenticatedLabPaletteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
